### ISSUE TITLE
merge_in_config fail

### ISSUE THREAD

**Issue by jolee11** [alexferl/vyper#14]
Hello, I cannot merge content from two config files. Please give me some help! Thank you very much!

----------------------------------------------
I have two yaml config files:

1.  x.yaml
    a: "abc"

2.  y.yaml
    a: "xyz"

-----------------------------------------------
The test.py is:

from vyper import v

v.add_config_path('.')
v.set_config_type('yaml')
v.set_config_name("x")
v.read_in_config()
print(v.get_string("a"))   # expect 'abc'

v.set_config_name("y")
v.merge_in_config()
print(v.get_string("a"))  # expect 'xyz'

'''
Actual output:

abc
Traceback (most recent call last):
  File "/Users/createtech/temp/pyvyper/vyper/util.py", line 56, in unmarshall_config_reader
    d.update(yaml.load(f))
ValueError: dictionary update sequence element #0 has length 1; 2 is required

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 11, in <module>
    v.merge_in_config()
  File "/Users/createtech/temp/pyvyper/vyper/vyper.py", line 535, in merge_in_config
    return self.merge_config(file_)
  File "/Users/createtech/temp/pyvyper/vyper/vyper.py", line 548, in merge_config
    cfg = self._unmarshall_reader(file_, cfg)
  File "/Users/createtech/temp/pyvyper/vyper/vyper.py", line 568, in _unmarshall_reader
    return util.unmarshall_config_reader(file_, d, self._get_config_type())
  File "/Users/createtech/temp/pyvyper/vyper/util.py", line 60, in unmarshall_config_reader
    raise ConfigParserError(e)
vyper.util.ConfigParserError: While parsing config: dictionary update sequence element #0 has length 1; 2 is required
'''

**Comment by admiralobvious** [comment]
Hi,

Sorry that issue slipped past me, I can confirm I have the same behaviour. I'll check it.

**Comment by jolee11** [comment]
Thank you very much!

**Comment by admiralobvious** [comment]
This is fixed in v0.3.3.
